export const ptBR = {
  layout: {
    appName: 'CROMia',
    dashboard: 'Painel Operacional',
    navigation: {
      operation: 'Operação',
      clients: 'Clientes',
      resources: 'Recursos',
      system: 'Sistema',
      approvals: 'Central de Aprovações',
      team: 'Gestão de Equipe',
      boards: 'Quadro Operacional',
      intake: 'Solicitações',
      calendar: 'Calendário Editorial',
      hub: 'Central Operacional',
      scheduling: 'Fila de Agendamento',
      scheduled: 'Posts Agendados',
      drive: 'Drive de Arquivos',
      documents: 'Documentos',
      finance: 'Financeiro',
      logs: 'Logs do Sistema',
      settings: 'Configurações',
    },
  },

  commandPalette: {
    searchPlaceholder: 'Pesquisar página ou comando...',
    emptyResults: (query: string) => `Nenhum resultado encontrado para "${query}"`,
    groups: {
      navigation: 'Navegação',
      actions: 'Comandos Rápidos',
    },
    shortcuts: {
      clear: 'limpar',
      navigate: 'ir para',
      open: 'abrir',
      reopen: 'Cmd+K para reabrir',
    },
  },

  upload: {
    title: 'Arraste os arquivos ou clique para selecionar',
    subtitle: 'Os arquivos serão enviados para o diretório atual.',
    button: 'Selecionar Arquivos',
    contextPrefix: 'Sugestão Operacional',
  },

  approvals: {
    title: 'Central de Aprovações',
    subtitle: 'Gerencie o fluxo de aprovação de conteúdos com links compartilháveis.',
    linkMissing: 'O link público ainda não foi gerado.',
    linkCopied: 'Link de acesso copiado com sucesso!',
    notifyWhatsapp: 'Notificar via WhatsApp',
    rejectedForReview: 'Aguardando Revisão Interna',
    emptyRejectedForReview: 'Nenhum item pendente de revisão no momento.',
    loading: 'Carregando dados...',
    notFound: 'Registro não encontrado.',
    back: 'Voltar para Lista',
    calendarBadge: 'Calendário Editorial',
    calendarBadgeShort: 'Calendário',
    pendingDecision: 'item(ns) aguardando decisão',
    postsTitle: 'Publicações',
    emptyPosts: 'Nenhuma publicação cadastrada neste pacote.',
    cancelBox: 'Esta ação cancelará a aprovação permanentemente.',
    cancelConfirm: 'Tem certeza que deseja cancelar esta aprovação?',
    cancelAction: 'Cancelar Aprovação',
    newApproval: 'Nova Solicitação de Aprovação',
    systemLabel: 'CROMiaOS',
    manualDisabledTitle: 'Fluxo Centralizado: Utilize o Calendário Editorial para criar aprovações.',
    manualDisabledButton: 'Aprovação Manual Desativada',
    emptySearch: 'Nenhum resultado para os filtros aplicados.',
    empty: 'Nenhuma aprovação registrada.',
    emptyHint: 'Fluxo ativo: Crie as publicações no Calendário e selecione "Enviar para Aprovação".',
    undefinedClient: 'Cliente não identificado',

    status: {
      pending: 'Pendente',
      approved: 'Aprovado',
      rejected: 'Reprovado',
      revisionRequested: 'Ajuste Solicitado',
      cancelled: 'Cancelado',
    },

    tabs: {
      all: 'Todos',
      pending: 'Pendentes',
      approved: 'Aprovados',
      revisionRequested: 'Em Revisão',
      rejected: 'Reprovados',
      cancelled: 'Cancelados',
    },

    actions: {
      approve: 'Aprovar Conteúdo ✅',
      requestReview: 'Solicitar Ajustes 🟡',
      reject: 'Reprovar Item ❌',
      approveAll: 'Aprovar Todos os Itens ✅',
      requestGeneralReview: 'Solicitar Revisão Geral 🟡',
      cancel: 'Fechar',
      creating: 'Processando solicitação...',
      createApproval: 'Criar Central de Aprovação',
    },

    summary: {
      total: 'Total de Itens',
      pending: 'Pendentes',
      approved: 'Aprovados',
      review: 'Ajustes',
    },

    meta: {
      client: 'Cliente',
      period: 'Período de Referência',
      created: 'Data de Criação',
    },

    item: {
      linkedCalendar: '📅 Item vinculado ao Calendário Editorial',
      reviewedBy: 'Revisado por',
      onDate: 'em',
      viewVideo: 'Visualizar Vídeo',
      textLabel: 'Conteúdo da Legenda',
      feedbackPlaceholder: 'Descreva os ajustes necessários...',
      platformLabel: 'Plataforma de Destino',
    },

    card: {
      posts: 'publicações',
      approvedCount: 'item(ns) aprovado(s)',
      publicLink: 'Link de Acesso Público',
    },

    form: {
      title: 'Título do Pacote',
      titlePlaceholder: 'Ex: Cronograma Social - Outubro 2026',
      client: 'Cliente Responsável',
      clientPlaceholder: 'Selecione ou digite o nome do cliente',
      month: 'Mês de Referência',
      year: 'Ano',
      description: 'Notas de Contexto',
      descriptionPlaceholder: 'Observações relevantes sobre este conjunto de posts',
      posts: 'Itens do Pacote',
      addPost: 'Adicionar Item',
      post: 'Item',
      platform: 'Canal de Veiculação',
      postTitle: 'Título do Item',
      postTitlePlaceholder: 'Tema ou ID da publicação',
      postText: 'Descrição / Legenda',
      postTextPlaceholder: 'Insira aqui o texto final da publicação',
      mediaUrl: 'Link da Mídia (URL)',
      publishDate: 'Data Programada',
    },

    searchPlaceholder: 'Pesquisar por título, cliente ou status...',
    copyLink: 'Copiar Link Público',
    openPage: 'Visualizar Página de Aprovação',
  },

  workflow: {
    status: {
      rascunho: 'Rascunho',
      revisaoInterna: 'Revisão interna',
      aprovadoInterno: 'Aprovado internamente',
      emAprovacaoCliente: 'Em aprovação do cliente',
      revisaoCliente: 'Revisão Solicitada pelo Cliente',
      aprovadoCliente: 'Aprovado pelo Cliente',
      aguardandoAgendamento: 'Aguardando Agendamento',
      agendado: 'Agendado',
      publicado: 'Publicado',
    },
    approval: {
      pending: 'Pendente de Decisão',
      approved: 'Aprovado para Publicação',
      changesRequested: 'Ajustes Pendentes',
      rejected: 'Conteúdo Descartado',
    },
  },

  calendar: {
    editor: {
      dayLabel: 'Dia Editorial',
      defaultCategory: 'Nova Publicação',
      editTitle: 'Gestão da Publicação',
      createTitle: 'Nova Publicação',
      category: 'Tipo de Conteúdo',
      workflowStatus: 'Etapa do Pipeline',
      socialNetworks: 'Canais de Distribuição',
      title: 'Título Estratégico',
      titlePlaceholder: 'Nome descritivo da publicação',
      description: 'Briefing do Conteúdo',
      descriptionPlaceholder: 'Conceito e objetivos da peça',
      internalNotes: 'Observações de Produção',
      notesPlaceholder: 'Diretrizes para design, CTAs e links...',
      image: 'Peça Gráfica (Imagem)',
      uploadImage: 'Carregar Imagem',
      noImage: 'Sem peça gráfica anexada',
      video: 'Arquivo de Vídeo',
      uploadVideo: 'Carregar Vídeo',
      noVideo: 'Sem vídeo anexado',
      changeReason: 'Alterações realizadas',
      changeReasonPlaceholder: 'Ex: Troca de imagem, ajuste de CTA, correção de texto...',
      scheduleDate: 'Data de publicação',
      scheduleTime: 'Horário de publicação',
      scheduleHint: 'Defina a data e hora para tirar o post do limbo operacional.',
      confirmSchedule: 'Confirmar agendamento',
      markPublished: 'Marcar como publicado',
      clientRevisionNote: 'Solicitação mais recente do cliente',
      versionHistory: 'Histórico de versões',
      currentVersion: 'Versão atual',
      previousVersion: 'Versão anterior',
      viewPreviousVersion: 'Ver versão anterior',
      latestVersionHint: 'Você está editando a versão mais recente.',
      footerHint: 'Atenção: Utilize o pipeline oficial para manter o status atualizado.',
      delete: 'Remover Publicação',
      cancel: 'Descartar Alterações',
      save: 'Atualizar Publicação',
      create: 'Confirmar Publicação',
    },
  },
} as const;

export type PtBrDictionary = typeof ptBR;
